// @vitest-environment node
import { describe, expect, it } from 'vitest'

import { DEFAULT_WEIGHTS, scheduleReview } from './fsrs.js'
import { MIN_REVIEWS_TO_FIT, averageLogLoss, fitWeights } from './fit-weights.js'

/* A small, seeded PRNG so the synthetic review logs below are exactly
 * reproducible — a flaky optimizer test is worse than no test, because it
 * teaches everyone to re-run rather than to read the failure. */
function mulberry32(seed) {
  let a = seed
  return function random() {
    a |= 0
    a = (a + 0x6d2b79f5) | 0
    let t = Math.imul(a ^ (a >>> 15), 1 | a)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

/**
 * A synthetic review log for one learner: many artefacts, each reviewed
 * several times, generated by *replaying* `scheduleReview` under a known
 * "true" weight vector so the outcome of each review is exactly what those
 * weights predict — rating 1 when the roll exceeds the true retrievability,
 * a rating in 2..4 otherwise. This is the only honest way to generate a log
 * a weight-fitting search should be able to recover something from: real
 * review logs are themselves generated by *some* underlying memory process,
 * and here we control what that process is.
 */
function syntheticLog({ trueWeights, artefactCount = 40, reviewsPerArtefact = 8, seed = 1 }) {
  const random = mulberry32(seed)
  const reviews = []
  let cursor = new Date('2026-01-01T00:00:00.000Z').getTime()

  for (let a = 0; a < artefactCount; a++) {
    const artefactId = `artefact-${a}`
    let state = null

    for (let r = 0; r < reviewsPerArtefact; r++) {
      // Space reviews out a plausible number of days, so elapsed time is
      // never zero and retrievability actually varies.
      cursor += (1 + Math.floor(random() * 6)) * 86_400_000
      const reviewedAt = new Date(cursor).toISOString()

      let rating
      if (!state) {
        rating = 3
      } else {
        const elapsedDays = Math.max(
          (cursor - new Date(state.last_reviewed_at).getTime()) / 86_400_000,
          0,
        )
        const roll = random()
        // Roughly graded: a clear miss is a 1, a narrow recall is a 2, a
        // comfortable one is a 3, and a very comfortable one is a 4 —
        // deliberately coarse, the same way a learner's actual ratings are.
        const p = Math.min(
          Math.max((1 + (19 / 81) * elapsedDays / Math.max(state.stability, 0.01)) ** -0.5, 0),
          1,
        )
        if (roll > p) rating = 1
        else if (roll > p * 0.6) rating = 2
        else if (roll > p * 0.2) rating = 3
        else rating = 4
      }

      reviews.push({ artefact_id: artefactId, rating, reviewed_at: reviewedAt })
      state = scheduleReview({ state, rating, now: reviewedAt, weights: trueWeights })
    }
  }

  return reviews
}

const TRUE_WEIGHTS = DEFAULT_WEIGHTS.map((w, i) =>
  // A learner who is not the average FSRS-4.5 subject: stability climbs
  // faster (w8 up) and difficulty resists change less (w6 down).
  i === 8 ? w * 1.4 : i === 6 ? w * 0.6 : w,
)

describe('averageLogLoss', () => {
  it('is null when no artefact has been reviewed more than once', () => {
    const reviews = [
      { artefact_id: 'a1', rating: 3, reviewed_at: '2026-01-01T00:00:00.000Z' },
      { artefact_id: 'a2', rating: 3, reviewed_at: '2026-01-01T00:00:00.000Z' },
    ]

    expect(averageLogLoss(reviews, DEFAULT_WEIGHTS)).toBeNull()
  })

  it('is a finite non-negative number once a card has come back around', () => {
    const reviews = syntheticLog({ trueWeights: TRUE_WEIGHTS, artefactCount: 5, reviewsPerArtefact: 4 })
    const loss = averageLogLoss(reviews, DEFAULT_WEIGHTS)

    expect(Number.isFinite(loss)).toBe(true)
    expect(loss).toBeGreaterThanOrEqual(0)
  })

  it('scores a wildly wrong weight vector worse than the true one', () => {
    const reviews = syntheticLog({ trueWeights: TRUE_WEIGHTS, artefactCount: 30, reviewsPerArtefact: 8 })

    const lossAtTruth = averageLogLoss(reviews, TRUE_WEIGHTS)
    const wrong = TRUE_WEIGHTS.map((w) => Math.max(w * 0.05, 0.05))
    const lossAtWrong = averageLogLoss(reviews, wrong)

    expect(lossAtTruth).toBeLessThan(lossAtWrong)
  })
})

describe('fitWeights', () => {
  it('refuses to pretend a handful of reviews is a fit', () => {
    const reviews = syntheticLog({ trueWeights: TRUE_WEIGHTS, artefactCount: 2, reviewsPerArtefact: 2 })
    expect(reviews.length).toBeLessThan(MIN_REVIEWS_TO_FIT)

    const fit = fitWeights(reviews)

    expect(fit.improved).toBe(false)
    expect(fit.reviewCount).toBe(reviews.length)
  })

  it('never returns a fit worse than the weights it started from', () => {
    const reviews = syntheticLog({ trueWeights: TRUE_WEIGHTS, artefactCount: 40, reviewsPerArtefact: 8 })
    expect(reviews.length).toBeGreaterThanOrEqual(MIN_REVIEWS_TO_FIT)

    const fit = fitWeights(reviews, { initialWeights: DEFAULT_WEIGHTS, maxPasses: 12 })

    expect(fit.loss).toBeLessThanOrEqual(fit.startingLoss)
  })

  it('moves the loss on this learner\'s data below the published defaults', () => {
    const reviews = syntheticLog({ trueWeights: TRUE_WEIGHTS, artefactCount: 60, reviewsPerArtefact: 10 })

    const fit = fitWeights(reviews, { initialWeights: DEFAULT_WEIGHTS, maxPasses: 20 })
    const defaultLoss = averageLogLoss(reviews, DEFAULT_WEIGHTS)

    expect(fit.loss).toBeLessThan(defaultLoss)
  })

  it('always returns exactly 17 finite weights, in bounds', () => {
    const reviews = syntheticLog({ trueWeights: TRUE_WEIGHTS, artefactCount: 40, reviewsPerArtefact: 8 })
    const fit = fitWeights(reviews, { maxPasses: 8 })

    expect(fit.weights).toHaveLength(17)
    for (const w of fit.weights) {
      expect(Number.isFinite(w)).toBe(true)
    }
  })

  it('is pure: the same log fits to the same weights every time', () => {
    const reviews = syntheticLog({ trueWeights: TRUE_WEIGHTS, artefactCount: 25, reviewsPerArtefact: 6 })

    const first = fitWeights(reviews, { maxPasses: 10 })
    const second = fitWeights(reviews, { maxPasses: 10 })

    expect(second.weights).toEqual(first.weights)
    expect(second.loss).toBe(first.loss)
  })

  it('does not touch a clock, the network or a database', () => {
    // No import in this file reaches outside src/lib/review, and fitWeights
    // takes its input as plain data — this test exists as a named contract
    // rather than a real assertion, so a future edit that adds an import
    // reaching outside this directory is at least announced by the name of
    // the test it (silently) stops testing.
    expect(typeof fitWeights).toBe('function')
  })
})
